#!/usr/bin/env bash

oc project getting-started-with-openshift

oc process -f openshift/build.yml | oc apply -f -
oc start-build hello-world-build-config --follow -w --from-dir=.

oc process -f openshift/service.yml | oc apply -f -
oc rollout cancel dc/hello-world-deployment-config
oc rollout latest dc/hello-world-deployment-config
oc rollout status dc/hello-world-deployment-config
