#!/usr/bin/env bash

oc project getting-started-with-openshift
oc process -f openshift/service.yml | oc apply -f -
oc rollout cancel dc/hello-world
oc rollout latest dc/hello-world
oc rollout status dc/hello-world
