---
kind: Template
apiVersion: v1
metadata:
  name: "${SERVICE_NAME}"
  creationTimestamp:
  annotations:
    description: "Application template for ${SERVICE_NAME}"
    tags: "${SERVICE_NAME},microservice"
    version: 1.0.0
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${SERVICE_NAME}"
      labels:
        app: "${SERVICE_NAME}"
    spec:
      clusterIP: None
      selector:
        deploymentconfig: "${SERVICE_NAME}"
      ports:
        - port: 8080
          targetPort: 8080
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: "${SERVICE_NAME}"
      app: "${SERVICE_NAME}"
    spec:
      selector:
        app: "${SERVICE_NAME}"
        deploymentconfig: "${SERVICE_NAME}"
      replicas: 1
      triggers: []
      template:
        metadata:
          labels:
            app: "${SERVICE_NAME}"
            deploymentconfig: "${SERVICE_NAME}"
        spec:
          containers:
            - name: hello-world
              image: springio/gs-spring-boot-docker
              ports:
                  - containerPort: 8080
parameters:
  - name: "SERVICE_NAME"
    value: "hello-world"